[2025-07-11T16:02:02.367+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_etl_dag.loading_data manual__2025-07-11T16:00:48.984577+00:00 [queued]>
[2025-07-11T16:02:02.382+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_etl_dag.loading_data manual__2025-07-11T16:00:48.984577+00:00 [queued]>
[2025-07-11T16:02:02.383+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-11T16:02:02.407+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): loading_data> on 2025-07-11 16:00:48.984577+00:00
[2025-07-11T16:02:02.417+0000] {standard_task_runner.py:60} INFO - Started process 118 to run task
[2025-07-11T16:02:02.424+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'flight_etl_dag', 'loading_data', 'manual__2025-07-11T16:00:48.984577+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/flight_etl_dag.py', '--cfg-path', '/tmp/tmpaw922swt']
[2025-07-11T16:02:02.425+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask loading_data
[2025-07-11T16:02:02.515+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_etl_dag.loading_data manual__2025-07-11T16:00:48.984577+00:00 [running]> on host faee04e61171
[2025-07-11T16:02:02.624+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='flight_etl_dag' AIRFLOW_CTX_TASK_ID='loading_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-11T16:00:48.984577+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-11T16:00:48.984577+00:00'
[2025-07-11T16:02:02.662+0000] {logging_mixin.py:188} INFO - Data to load:
[2025-07-11T16:02:02.682+0000] {logging_mixin.py:188} INFO -   aircraft_id flight_number origin_country  ...  position_source      time       date
0      a34215                United States  ...            ADS-B  11:00:08 2025-07-11
1      39de42      TVF96ZB          France  ...            ADS-B  11:00:08 2025-07-11
2      3c5ee3                      Germany  ...            ADS-B  10:59:34 2025-07-11
3      a3428e                United States  ...            ADS-B  10:59:58 2025-07-11
4      4aca83                       Sweden  ...            ADS-B  10:58:35 2025-07-11

[5 rows x 11 columns]
[2025-07-11T16:02:02.702+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/load.py", line 20, in load_to_db
    create_tables()
  File "/opt/airflow/db_schema.py", line 8, in create_tables
    cursor.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(aircraft, 2200) already exists.

[2025-07-11T16:02:02.725+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=flight_etl_dag, task_id=loading_data, execution_date=20250711T160048, start_date=20250711T160202, end_date=20250711T160202
[2025-07-11T16:02:02.747+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task loading_data (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(aircraft, 2200) already exists.
; 118)
[2025-07-11T16:02:02.799+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-11T16:02:02.824+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
